<a href="https://colab.research.google.com/github/Marcelo-Silvestre/Analise_Dados_Boas_Praticas_PUCRIO/blob/main/Notebooks/jogos_estudo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
url_base = pd.read_excel("https://raw.githubusercontent.com/Marcelo-Silvestre/Estudo_jogos/main/bases/Lotof%C3%A1cil.xlsx")

In [6]:
df_jogos = pd.DataFrame(url_base)
df_jogos.head()

,Concurso,Data Sorteio,Bola1,Bola2,Bola3,Bola4,Bola5,Bola6,Bola7,Bola8,...,Rateio 13 acertos,Ganhadores 12 acertos,Rateio 12 acertos,Ganhadores 11 acertos,Rateio 11 acertos,Acumulado 15 acertos,Arrecadacao Total,Estimativa Prêmio,Acumulado sorteio especial Lotofácil da Independência,Observação
0,1,29/09/2003,2,3,5,6,9,10,11,13,...,"R$10,00",48807,"R$4,00",257593,"R$2,00","R$0,00","R$0,00","R$0,00","R$0,00",Estimativa de prêmio (15 ACERTOS) próximo conc...
1,2,06/10/2003,1,4,5,6,7,9,11,12,...,"R$10,00",81252,"R$4,00",478188,"R$2,00","R$0,00","R$0,00","R$0,00","R$0,00",ESTIMATIVA DE PRÊMIO PARA O PRÓXIMO CONCURSO (...
2,3,13/10/2003,1,4,6,7,8,9,10,11,...,"R$10,00",96244,"R$4,00",608211,"R$2,00","R$0,00","R$0,00","R$0,00","R$0,00",Estimativa de prêmio (15 ACERTOS) próximo conc...
3,4,20/10/2003,1,2,4,5,8,10,12,13,...,"R$10,00",123912,"R$4,00",706657,"R$2,00","R$0,00","R$0,00","R$0,00","R$0,00",Estimativa de prêmio (15 ACERTOS) próximo conc...
4,5,27/10/2003,1,2,4,8,9,11,12,13,...,"R$10,00",195636,"R$4,00",860992,"R$2,00","R$0,00","R$0,00","R$0,00","R$0,00",Estimativa de prêmio para o próximo concurso (...

In [11]:
df_sorteados = df_jogos.iloc[:,2:17]
df_sorteados

,Bola1,Bola2,Bola3,Bola4,Bola5,Bola6,Bola7,Bola8,Bola9,Bola10,Bola11,Bola12,Bola13,Bola14,Bola15
0,2,3,5,6,9,10,11,13,14,16,18,20,23,24,25
1,1,4,5,6,7,9,11,12,13,15,16,19,20,23,24
2,1,4,6,7,8,9,10,11,12,14,16,17,20,23,24
3,1,2,4,5,8,10,12,13,16,17,18,19,23,24,25
4,1,2,4,8,9,11,12,13,15,16,19,20,23,24,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3653,1,2,3,4,6,7,11,15,17,19,20,22,23,24,25
3654,1,2,4,5,6,10,11,12,17,18,19,21,22,23,24
3655,3,4,6,7,8,11,12,14,15,18,19,20,21,24,25
3656,1,2,4,7,8,10,12,13,17,18,19,20,22,23,24
3657,2,3,4,5,9,10,11,12,13,16,18,20,22,23,24

In [104]:
df_bola1 = df_sorteados['Bola1'].unique()
df_bola1

array([2, 1, 3, 5, 4, 6, 7, 9])

In [105]:
sorteio_bola1_1 = df_sorteados[df_sorteados['Bola1'] == 1]
sorteio_bola1_1

,Bola1,Bola2,Bola3,Bola4,Bola5,Bola6,Bola7,Bola8,Bola9,Bola10,Bola11,Bola12,Bola13,Bola14,Bola15
1,1,4,5,6,7,9,11,12,13,15,16,19,20,23,24
2,1,4,6,7,8,9,10,11,12,14,16,17,20,23,24
3,1,2,4,5,8,10,12,13,16,17,18,19,23,24,25
4,1,2,4,8,9,11,12,13,15,16,19,20,23,24,25
5,1,2,4,5,6,7,10,12,15,16,17,19,21,23,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3647,1,2,5,7,8,9,10,11,13,14,15,18,19,20,22
3651,1,3,6,7,11,12,13,15,16,18,19,20,21,23,24
3653,1,2,3,4,6,7,11,15,17,19,20,22,23,24,25
3654,1,2,4,5,6,10,11,12,17,18,19,21,22,23,24
3656,1,2,4,7,8,10,12,13,17,18,19,20,22,23,24

In [107]:
print(len(sorteio_bola1_2))

899

In [108]:
df_bola2 = df_sorteados['Bola2'].unique()
df_bola2

array([ 3,  4,  2,  5,  6,  7,  8,  9, 10])

In [109]:
print(len(df_bola2))

9

In [ ]:
sorteio_bola1_2 = df_sorteados[df_sorteados['Bola1'] == 2]
sorteio_bola1_2

,Bola1,Bola2,Bola3,Bola4,Bola5,Bola6,Bola7,Bola8,Bola9,Bola10,Bola11,Bola12,Bola13,Bola14,Bola15
0,2,3,5,6,9,10,11,13,14,16,18,20,23,24,25
9,2,3,4,5,6,8,9,10,11,12,14,19,20,23,24
10,2,6,7,8,9,10,11,12,16,19,20,22,23,24,25
15,2,5,6,7,8,10,12,13,15,17,19,21,23,24,25
17,2,6,7,8,10,11,14,15,17,18,19,20,22,23,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3646,2,4,5,8,10,12,15,16,17,19,20,21,22,24,25
3649,2,5,6,7,8,10,11,12,13,16,17,20,21,22,25
3650,2,3,5,8,10,12,13,14,16,17,18,20,21,24,25
3652,2,3,4,6,7,8,10,11,13,14,16,18,19,20,21
3657,2,3,4,5,9,10,11,12,13,16,18,20,22,23,24

In [110]:
print(len(sorteio_bola1_2))

899

In [81]:
df_bola3 = df_sorteados['Bola3'].unique()
df_bola3

array([ 5,  6,  4,  7,  3,  8,  9, 11, 10, 12])

In [83]:
print(len(df_bola3))

10

In [74]:
df_bola4 = df_sorteados['Bola4'].unique()
df_bola4

array([ 6,  7,  5,  8,  9,  4, 10, 12, 11, 13])

In [84]:
print(len(df_bola4))

10

In [73]:
df_bola5 = df_sorteados['Bola5'].unique()
df_bola5

array([ 9,  7,  8,  6, 10,  5, 11, 12, 13, 14])

In [85]:
print(len(df_bola5))

10

In [72]:
df_bola6 = df_sorteados['Bola6'].unique()
df_bola6

array([10,  9, 11,  7, 12,  8,  6, 13, 15, 14, 16])

In [86]:
print(len(df_bola6))

11

In [71]:
df_bola7 = df_sorteados['Bola7'].unique()
df_bola7

array([11, 10, 12, 14, 13,  9,  7,  8, 15, 16, 17])

In [87]:
print(len(df_bola7))

11

In [70]:
df_bola8 = df_sorteados['Bola8'].unique()
df_bola8

array([13, 12, 11, 15, 10, 14, 16,  9, 17,  8, 18])

In [88]:
print(len(df_bola8))

11

In [69]:
df_bola9 = df_sorteados['Bola9'].unique()
df_bola9

array([14, 13, 12, 16, 15, 11, 17, 18, 10, 19,  9])

In [89]:
print(len(df_bola9))

11

In [68]:
df_bola10 = df_sorteados['Bola10'].unique()
df_bola10

array([16, 15, 14, 17, 18, 12, 19, 13, 20, 11, 10])

In [90]:
print(len(df_bola10))

11

In [64]:
df_bola11 = df_sorteados['Bola11'].unique()
df_bola11

array([18, 16, 19, 17, 14, 20, 15, 13, 21, 12])

In [91]:
print(len(df_bola11))

10

In [62]:
df_bola12 = df_sorteados['Bola12'].unique()
df_bola12

array([20, 19, 17, 21, 22, 16, 18, 14, 15, 13])

In [92]:
print(len(df_bola12))

10

In [61]:
df_bola13 = df_sorteados['Bola13'].unique()
df_bola13

array([23, 20, 21, 22, 17, 19, 15, 18, 16])

In [93]:
print(len(df_bola13))

9

In [59]:
df_bola14 = df_sorteados['Bola14'].unique()
df_bola14

array([24, 23, 22, 19, 20, 21, 18, 17])

In [94]:
print(len(df_bola14))

8

In [57]:
df_bola15 = df_sorteados['Bola15'].unique()
df_bola15

array([25, 24, 23, 21, 20, 22, 19, 18])

In [95]:
print(len(df_bola15))

8